### ISSUE TITLE
The project is frozen?

### ISSUE THREAD

**Issue by brightproject** [peterashwoodsmith/ArtificialHorizon#1]
Tell me, did your horizon line remain in a roll when you tilted the sensor or slowly returned to the beginning?
![Скриншот 12-08-2023 20 06 07](https://github.com/peterashwoodsmith/ArtificialHorizon/assets/1788098/c89dcc93-1111-4cee-b138-e520037acfac)

https://www.youtube.com/watch?v=mU1mT4dsyRU

**Comment by peterashwoodsmith** [comment]
Nice, no it stayed. Im guessing you are reading accelleration x,y,z and not the gyro oroentation x,y,z?PeterOn Aug 12, 2023, at 1:34 PM, Vladislav ***@***.***> wrote:﻿
Tell me, did your horizon line remain in a roll when you tilted the sensor or slowly returned to the beginning?

https://www.youtube.com/watch?v=mU1mT4dsyRU

**Comment by brightproject** [comment]
May I ask you to help me with this question?
I use such a board in the device
![BMI160](https://github.com/hanyazou/BMI160-Arduino/assets/1788098/c9808d64-8e37-45de-aa8e-b612abdabbdb)

Based on examle [code](https://github.com/mjs513/Modified-BMI160---BMM150-Arduino-Libraries/blob/master/BMI160-Arduino/examples/Gyro/Gyro.ino)

only placing it not horizontally, but vertically.
![Скриншот 10-08-2023 19 36 00](https://github.com/hanyazou/BMI160-Arduino/assets/1788098/1d85da52-ded5-474f-94cd-549439cf14f0)

How to remap the axes, I did not find another way how to do remapping through Bosch software.

I pass the data through the Madgwick filter and get the roll, pitch and heading angles at the output.
But if I use this data when the board is in a vertical position, I have very small movements, due to the lack of axes.
But if I [use](https://docs.arduino.cc/library-examples/curie-imu/Genuino101CurieIMUOrientationVisualiser) the received data for processing and visualize them using the transformation matrix, then all rotations of the body are normally performed.
![Скриншот 10-08-2023 22 58 59](https://github.com/hanyazou/BMI160-Arduino/assets/1788098/665fac49-14ef-422f-8a4c-94287aa7a4be)

As far as I understand, there are two ways to solve the problem with the orientation of the axes:
1. changing raw data directly in the Bosch sensor
2. application of the transformation matrix, but this requires the computing power of the microcontroller
Unfortunately, I did not find working examples with axis orientation for BMI160.
I try apply calibration offsets also
```
    BMI160.autoCalibrateGyroOffset();

    BMI160.autoCalibrateAccelerometerOffset(X_AXIS, 0);
    BMI160.autoCalibrateAccelerometerOffset(Y_AXIS, 0);
    BMI160.autoCalibrateAccelerometerOffset(Z_AXIS, 1);
```
While I do not understand the functions `autoCalibrateAccelerometerOffset` and `autoCalibrateGyroOffset`  well enough, it seems to me that it should set the value of accelerometers and accelerations to zero when the board is placed in the desired position (on its side, upside down, at an angle) and start counting from a calibrated "point".
Or am I misinterpreting the `autoCalibrateAccelerometerOffset` and `autoCalibrateGyroOffset` functionality?

**Comment by peterashwoodsmith** [comment]
Look at the sampleBNO function. You can simply change x,y,z without any matrix math because they are all 90 or 180 degrees. 
so set *ox etc to the appropriate imu axis. 

The project is not frozen, I just got bored :) 

inline bool sampleBNO(float *ox, float *oy, float *oz, float *os)
{
     imu::Vector<3> imudata;
     //
     imudata = bno.getVector(Adafruit_BNO055::VECTOR_EULER);
     *ox = imudata.x();
     *oy = imudata.y();
     *oz = imudata.z();

**Comment by brightproject** [comment]
Thanks for the response, but you are not quite right.
I managed to deal with the problem by delving into the operation of the `Madjwick` filter, normalizing the quaternion and understanding the operation of the `bmi160` sensor.
The first thing I did was determine what my axes would look like by default when the sensor board is in a horizontal position.
This is the so-called `ENU` axis arrangement.
![imageAxis](https://github.com/peterashwoodsmith/ArtificialHorizon/assets/1788098/cd4b2414-d979-4c11-8663-a57290020f29)

The second point, I needed to determine in which direction the sensor determines the rotation around the axis as "positive".
I solved the first moment by calibrating the sensor readings, at the moment of start - the so-called `offsets.`
`//     Ax      Ay      Az`
`a:    1.00    0.02    0.05`

```
BMI160.autoCalibrateAccelerometerOffset(X_AXIS, 1);
BMI160.autoCalibrateAccelerometerOffset(Y_AXIS, 0);
BMI160.autoCalibrateAccelerometerOffset(Z_AXIS, 0);
```
Having previously set the new location of the accelerometer axis X as a unit, because in the vertical position on the axis of the Y and Z there is an overload of 0 gravity.
The second moment made me sweat and pretty strain my brains, because I couldn’t deal with the problem right away.
As you can see from my drawing, when the sensor is rotated from a horizontal to a vertical plane, the z-axis changes places with the x-axis.
The y-axis remains and does not change the direction of rotation.
The x-axis also does not change the rotation.
But the new position of the z-axis also changes its rotation, from positive to negative, so you need to change the sign for the variables az and gz before substituting them into the Madgwick filter.
![change_axis](https://github.com/peterashwoodsmith/ArtificialHorizon/assets/1788098/b21b2aa2-62bc-483c-bcba-54e1cb89b19d)

```
    // update the filter, which computes orientation

				   // z   x
				   // |  /
				   // | /
		   	    // y______|/

    // filter.updateIMU(gx, gy, gz, az, ay, ax);
	
// when changed the orientation of the axes, x became z, and z became x, 
//turned the board from the sensors from horizontal to vertical, you need to put signs 
//in front of the axes of z, first change these axes in the code (x from z)z
	
				   // x
				   // |
				   // |
			    // y______|
				  // /
				 // /  
				// z
    filter.updateIMU(-gz, gy, gx, -az, ay, ax);
```
I thought of all this empirically, having spent more than a dozen experiments and downloading the code into the device.
Prior to this, the data from the filter was not entirely predictable.

**Comment by brightproject** [comment]
The only thing that I didn’t understand was what kind of register, in the datasheet it is somehow connected with orientation, but there is very little information, and for some reason this register is associated with interrupts.
![Скриншот 14-08-2023 11 35 12](https://github.com/peterashwoodsmith/ArtificialHorizon/assets/1788098/c1822e44-1a71-4379-b6fb-39b423be75f2)

![Скриншот 14-08-2023 11 38 28](https://github.com/peterashwoodsmith/ArtificialHorizon/assets/1788098/c15ce355-f592-44db-93a4-4bbf385dd21d)

![Скриншот 14-08-2023 11 38 50](https://github.com/peterashwoodsmith/ArtificialHorizon/assets/1788098/6cb2a11d-fc70-4cc9-8404-90686c4cdf4b)

[BST-BMI160-DS000-1509569.pdf](https://github.com/peterashwoodsmith/ArtificialHorizon/files/12333050/BST-BMI160-DS000-1509569.pdf)

Is it a change of orientation or is it just fixing the turns and issuing an interrupt signal ... everything is very confusing.
